{
 "title": "igate.nayr.net",
 "description": "EastRidge iGate & DenCO Digi",
 "tags": [ "aprs" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Welcome",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "> System: [igate.nayr.net](https://igate.nayr.net)\n* Debian Buster LXC in Failover Cluster (4c x86_64/256m RAM)\n* Direwolf 1.5 TNC/APRS Transcoder ([full console](https://igate.nayr.net/direwolf))\n* Kenwood VHF TM-281a at **25W** on **144.39MHz** with Astron PSU\n* Diamond F22A 10.5' Monoband Antenna (6.7dB) on a Rohn Tripod\n* Two SignaLink USB Radio Interfaces (discriminator output / failover config)\n\n> Station Info: [N4YRE](https://aprs.fi/info/a/N4YRE)\n* Digipeater Path: **WIDEn-N,COn-N** (trapping > WIDE2)\n  * Digi Filter: source geofenced for mostly central Denver ([i25-i70-i225 loop](https://igate.nayr.net/digi-fence.png))\n* IS->RF Path: **WIDE2-1**\n  * Filter: **all messages to stations recieved within 1 hop in last hour**\n  * Filter Bypass: **NWS & Groups: ARES, 4X4RNR, SAR***\n* RF Beacon Interval: **30min WIDE2-1** (same path as messaging filter)\n* Contact: Ryan Hunt / admin at nayr dot net"
   },
   "content": "> System: [igate.nayr.net](https://igate.nayr.net)\n* Debian Buster LXC in Failover Cluster (4c x86_64/256m RAM)\n* Direwolf 1.5 TNC/APRS Transcoder ([full console](https://igate.nayr.net/direwolf))\n* Kenwood VHF TM-281a at **25W** on **144.39MHz** with Astron PSU\n* Diamond F22A 10.5' Monoband Antenna (6.7dB) on a Rohn Tripod\n* Two SignaLink USB Radio Interfaces (discriminator output / failover config)\n\n> Station Info: [N4YRE](https://aprs.fi/info/a/N4YRE)\n* Digipeater Path: **WIDEn-N,COn-N** (trapping > WIDE2)\n  * Digi Filter: source geofenced for mostly central Denver ([i25-i70-i225 loop](https://igate.nayr.net/digi-fence.png))\n* IS->RF Path: **WIDE2-1**\n  * Filter: **all messages to stations recieved within 1 hop in last hour**\n  * Filter Bypass: **NWS & Groups: ARES, 4X4RNR, SAR***\n* RF Beacon Interval: **30min WIDE2-1** (same path as messaging filter)\n* Contact: Ryan Hunt / admin at nayr dot net"
  },
  {
   "title": "All Rx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_rf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "Local Rx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_loc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "Direct Rx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_dir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "Digi Tx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_digi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "RF Tx Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "APRS Packets" }
   ],
   "targets": [
    {
     "alias": "Packets Digipeated",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dwstats_digi",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    },
    {
     "alias": "Messages Tx",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dwstats_msg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    },
    {
     "alias": "Internet Packets Tx",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dwstats_pkt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "APRS Stations Rx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Radio Stations" }
   ],
   "targets": [
    {
     "alias": "All Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_rf",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    },
    {
     "alias": "Local Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_loc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    },
    {
     "alias": "Direct Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_dir",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "Messages Tx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_msg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "APRS-IS Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "APRS Packets" }
   ],
   "targets": [
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_up",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    },
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_down",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "5m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "Packets Tx",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dwstats_pkt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "direwolf" }
     ]
    }
   ]
  },
  {
   "title": "Positions Rx via RF",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 10, "x": 14, "y": 10 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "dwlogs",
     "query": "SELECT longitude AS \"longitude\", \"latitude\" AS \"latitude\", \"chan\" +1 FROM \"dwlogs\" WHERE (\"path\" = '/var/log/direwolf/direwolf.log') AND time >= now() - 1h GROUP BY \"name\" LIMIT 100",
     "select": [
      [
       { "params": [ "longitude" ], "type": "field" },
       { "params": [ "longitude" ], "type": "alias" }
      ],
      [
       { "params": [ "latitude" ], "type": "field" },
       { "params": [ "latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "chan" ], "type": "field" },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/var/log/direwolf/direwolf.log" }
     ]
    }
   ]
  },
  {
   "title": "DireWolf Console (Realtime)",
   "type": "text",
   "description": "[Scrollable Full Screen](https://igate.nayr.net/direwolf)",
   "gridPos": { "h": 19, "w": 14, "x": 0, "y": 13 },
   "options": {
    "content": "<iframe src=\"https://igate.nayr.net/direwolf/\" scrolling=\"no\" style=\"top:0; left:0; bottom:0; right:0; width:100%; height: 99% ;border:none; margin:0; padding:0;\"></iframe>"
   },
   "content": "<iframe src=\"https://igate.nayr.net/direwolf/\" scrolling=\"no\" style=\"top:0; left:0; bottom:0; right:0; width:100%; height: 99% ;border:none; margin:0; padding:0;\"></iframe>"
  }
 ]
}